"""Generate SUMMARY.md from the consolidated run's own artifacts.

Every number is read from `outputs/three_head/`, never transcribed by hand, so
re-running the pipeline and re-running this script keeps the document honest.
"""
from __future__ import annotations

import json
import statistics
import subprocess
import sys
from pathlib import Path


EXPERIMENT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = EXPERIMENT_ROOT / "outputs" / "three_head"


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def log_excerpt(path: Path, keep_head: int = 6, keep_tail: int = 26) -> list[str]:
    lines = [line.rstrip() for line in path.read_text(encoding="utf-8").splitlines()]
    lines = [line for line in lines if line]
    if len(lines) <= keep_head + keep_tail:
        return lines
    elided = len(lines) - keep_head - keep_tail
    return (
        lines[:keep_head]
        + [f"... {elided} lines elided (full log in outputs/three_head/run_log.txt) ..."]
        + lines[-keep_tail:]
    )


def main() -> int:
    protocol = read_json(EXPERIMENT_ROOT / "configs" / "three_head_protocol.json")
    results = read_json(OUTPUT_ROOT / "report" / "three_head_results.json")
    training = read_json(OUTPUT_ROOT / "training_summary.json")
    manifest = read_json(OUTPUT_ROOT / "collection_manifest.json")
    run_log = OUTPUT_ROOT / "run_log.txt"

    collection_seconds = sum(record["seconds"] for record in manifest["records"])
    heads = training["heads"]
    head_metrics = results["head_metrics"]
    ratios = results["conditional_to_exact_floor_ratio"]
    correlation = results["correlation_metrics"]
    distribution = results["distribution"]
    distribution_ratio = results["distribution_to_exact_floor_ratio"]
    structure = results["structure"]
    counts = results["counts"]

    torch_version = subprocess.run(
        [sys.executable, "-c", "import torch;print(torch.__version__)"],
        capture_output=True, text=True,
    ).stdout.strip()

    lines: list[str] = []
    add = lines.append

    add("# Ideal-Conductance Dynamic Surrogate — Consolidated Summary")
    add("")
    add("This directory is the standalone home of the current three-head surrogate.")
    add("It contains the architecture, the tuned configuration, the trained")
    add("checkpoints, and a full from-scratch verification run.")
    add("")
    add("Generated by `scripts/write_summary.py` from the artifacts under")
    add("`outputs/three_head/`. Do not edit by hand; re-run the script instead.")
    add("")

    add("## The question")
    add("")
    add("For **one fixed weight and one fixed ideal conductance tensor `G_ideal`**,")
    add("can three conditional heads predict the `S_tile` output distribution that")
    add("*dynamic* read and voltage noise produces on held-out inputs?")
    add("")
    add("The learned object is `p(Y | X, G_ideal, hardware_config)`. Write variation")
    add("and stuck faults are disabled — they are neither inputs nor part of the")
    add("target, so this is not a device-population model.")
    add("")

    add("## Architecture")
    add("")
    add("Three heads over the same 100 valid `S_tile` coordinates, all conditioned")
    add("on features that are deterministic functions of the input, `G_ideal`, the")
    add("layout and the hardware config — never of a realized `G_static`, a write")
    add("seed, or a stochastic trace.")
    add("")
    add("| Head | Predicts | Parameterization | Features |")
    add("|---|---|---|---|")
    add("| Mean | residual `E[S] - nominal_S` | per-coordinate encoder + context pooling + fusion, zero-init output | 138 |")
    add("| Variance | clamped log-ratio vs a global per-coordinate variance | same architecture, different target | 138 |")
    add("| Correlation | full 100x100 correlation | factor model over the physical noise sources | 118 |")
    add("")
    add("### The correlation head is the substantive change")
    add("")
    add("An `S_tile` coordinate is `(k_block, row_index, out_index)`. It reads")
    add("voltages on its own row inside its own `k_block`, and conductance cells in")
    add("its own output column inside its own `k_block`. Two coordinates are")
    add("therefore functions of **disjoint** random variables unless they share a")
    add("`k_block` *and* (a row *or* an output column) — for every other pair the")
    add("covariance is exactly zero, by independence rather than by linearization.")
    add("")
    add(f"Only {protocol['source_structure']['structurally_nonzero_offdiagonal_entries']:,} "
        "of the 9,900 off-diagonal entries can be non-zero. This run measures:")
    add("")
    add("| Pair type | Pairs | RMS rho | Share of off-diagonal energy |")
    add("|---|---:|---:|---:|")
    labels = {
        "shared_row": "same k, shared row",
        "shared_out": "same k, shared output column",
        "same_k_disjoint": "same k, disjoint (exactly 0 in truth)",
        "cross_k_block": "different k_block (exactly 0 in truth)",
    }
    for key, label in labels.items():
        record = structure[key]
        add(f"| {label} | {record['pair_count']:,} | {record['rms_rho']:.4f} | "
            f"{100 * record['share_of_offdiagonal_energy']:.1f}% |")
    add("")
    noise_floor = (1.0 / counts["test_exact_samples_per_context"]) ** 0.5
    add(f"The two rows that must be zero sit at RMS "
        f"{structure['same_k_disjoint']['rms_rho']:.4f} and "
        f"{structure['cross_k_block']['rms_rho']:.4f} against a pure-noise")
    add(f"prediction of {noise_floor:.4f} — they carry only sampling noise.")
    add("")
    add("Each coordinate is written as a unit-variance sum over those sources:")
    add("")
    add("```text")
    add("S_d = <alpha_d, eps_voltage[k, row]> + <beta_d, eps_conductance[k, out]>")
    add("      + sqrt(1 - |alpha_d|^2 - |beta_d|^2) * eta_d")
    add("```")
    add("")
    add("Properties that hold by construction rather than by fitting: coordinates")
    add("sharing no source are exactly uncorrelated; the matrix is positive")
    add("semi-definite for any parameter value; the diagonal is exactly one; and")
    add("sampling is native, with no Cholesky factorization.")
    add("")
    add("`features.py` already stores the analytic loading as the unit-norm first 48")
    add("feature dimensions, so `[alpha ; beta]` has a closed-form value. The network")
    add("predicts only a bounded, zero-initialized correction to its direction plus a")
    add("per-coordinate explained-variance fraction — training *starts* at the")
    add("closed-form solution and is penalized for leaving it.")
    add("")

    add("## Methodology")
    add("")
    add("**Fail closed.** `configs/three_head_protocol.json` is hashed into a")
    add("`protocol_fingerprint` stamped on every shard, checkpoint and report. Any")
    add("artifact whose fingerprint disagrees is a hard error, never a silent")
    add("recompute. Shards are written atomically and carry a `checks` dict; the key")
    add("check is that the tail reconstruction reproduces the engine's own linear")
    add("output to 1e-5, which is what licenses the `S_tile`-space formulation.")
    add("")
    add("**Model selection uses validation only.** The test split is read once, at")
    add("`analyze`. Head schedules and the correlation regularizer were chosen on")
    add("validation across multiple seeds.")
    add("")
    add("**Three correlation metrics are reported.** The legacy full-matrix")
    add("Frobenius divides by a norm that includes the 100 unit diagonal entries,")
    add("compressing every score; it is kept for comparability. Off-diagonal-only")
    add("puts identity at exactly 1.0. Support-only scores the entries that can")
    add("physically be non-zero, and is the one that measures the model rather than")
    add("the reference's sampling noise.")
    add("")
    add("**`exact_independent_split` is not a lower bound.** It is the distance")
    add("between *two noisy draws* of the same size, so a good deterministic")
    add("predictor can legitimately score below it. A floor ratio above 1.0 is not by")
    add("itself evidence of a bad head, and one below 1.0 is not an impossibility.")
    add("")

    add("## Results from this run")
    add("")
    add(f"{counts['train_contexts']} train / {counts['validation_contexts']} validation / "
        f"{counts['test_contexts']} test contexts; "
        f"{counts['test_exact_samples_per_context']:,} Exact samples per test context")
    add(f"split 1024 candidate / 1024 reference; "
        f"{counts['test_surrogate_samples_per_context']:,} surrogate samples per context.")
    add("")
    add("### Head diagnostics on held-out test contexts")
    add("")
    add("| Metric | Exact floor | Conditional | Shuffled features | Shared | Floor ratio |")
    add("|---|---:|---:|---:|---:|---:|")
    metric_labels = {
        "mean": "Mean NRMSE",
        "variance": "Variance L1",
        "correlation": "Correlation Fro. (support)",
    }
    for head in ("mean", "variance", "correlation"):
        record = head_metrics[head]
        add(f"| {metric_labels[head]} | {record['exact_independent_split']['mean']:.4f} | "
            f"**{record['conditional']['mean']:.4f}** | "
            f"{record['shuffled_input_features']['mean']:.4f} | "
            f"{record['shared']['mean']:.4f} | {ratios[head]:.3f} |")
    add("")
    add("`shuffled_input_features` rolls the features by one context, destroying the")
    add("conditioning while preserving the marginals; `shared` is the")
    add("context-independent predictor. Both are far worse than the conditional")
    add("heads, which is what shows the heads use the conditioning.")
    add("")

    add("### Correlation predictors")
    add("")
    add("| Predictor | Full matrix | Off-diagonal | Support only |")
    add("|---|---:|---:|---:|")
    for name, record in correlation.items():
        highlight = "**" if name == "structured_conditional" else ""
        add(f"| `{name}` | {record['full_matrix_frobenius']['mean']:.4f} | "
            f"{record['offdiagonal_frobenius']['mean']:.4f} | "
            f"{highlight}{record['support_frobenius']['mean']:.4f}{highlight} |")
    add("")
    add("`analytic_first_order` has zero parameters and no training: it is the")
    add("closed-form covariance built from the stored source loadings. It is the")
    add("ablation that separates how much of the result is physics from how much is")
    add("learning.")
    add("")

    add("### End-to-end distribution")
    add("")
    for space in ("s_tile", "linear_output"):
        add(f"#### {space}")
        add("")
        add("| Method | Mean NRMSE | Variance L1 | Covariance Fro. | Quantile NRMSE | Sliced W. |")
        add("|---|---:|---:|---:|---:|---:|")
        for method, spaces in distribution.items():
            metrics = spaces[space]
            add(f"| `{method}` | {metrics['mean_nrmse']['mean']:.4f} | "
                f"{metrics['variance_relative_l1']['mean']:.4f} | "
                f"{metrics['covariance_relative_frobenius']['mean']:.4f} | "
                f"{metrics['quantile_nrmse']['mean']:.4f} | "
                f"{metrics['sliced_wasserstein']['mean']:.4f} |")
        add("")
    add("#### Distance to the Exact finite-sample floor")
    add("")
    add("1.000 means the surrogate is as close to the Exact reference as another")
    add("independent Exact draw of the same size.")
    add("")
    add("| Method | s_tile covariance | linear_output variance | linear_output covariance |")
    add("|---|---:|---:|---:|")
    for method, spaces in distribution_ratio.items():
        if method == "nominal_only":
            continue
        add(f"| `{method}` | {spaces['s_tile']['covariance_relative_frobenius']:.3f} | "
            f"{spaces['linear_output']['variance_relative_l1']:.3f} | "
            f"{spaces['linear_output']['covariance_relative_frobenius']:.3f} |")
    add("")

    add("### Training convergence")
    add("")
    add("A converged run is smooth late and does not peak on its final step.")
    add("Roughness is the mean absolute change between consecutive validation")
    add("reports over the second half of training.")
    add("")
    add("| Head | Best validation | At step | Reports | Late roughness | Best = final step |")
    add("|---|---:|---:|---:|---:|---:|")
    for head in ("mean", "variance", "correlation"):
        record = heads[head]
        curve = record["curve"]
        total = protocol["heads"][head]["steps"]
        add(f"| {head} | {record['best_validation']:.6f} | {record['best_step']}/{total} | "
            f"{curve['report_count']} | {curve['late_curve_roughness']:.6f} | "
            f"{'yes' if curve['best_is_final_step'] else 'no'} |")
    add("")

    add("## Reproducing this run")
    add("")
    add("```powershell")
    add("# Full pipeline from scratch (collect -> train -> analyze)")
    add("python .\\scripts\\run_three_head.py all --device cuda:0")
    add("")
    add("# Individual stages; each is resumable and safe to re-run")
    add("python .\\scripts\\run_three_head.py collect --device cuda:0")
    add("python .\\scripts\\run_three_head.py train   --device cuda:0")
    add("python .\\scripts\\run_three_head.py analyze --device cuda:0")
    add("")
    add("# Regenerate this document from the artifacts")
    add("python .\\scripts\\write_summary.py")
    add("")
    add("# Tests")
    add("python -m unittest discover -s tests -v")
    add("```")
    add("")
    add(f"Environment: Python {sys.version.split()[0]}, torch {torch_version}, ")
    add(f"single CUDA device. Collection took {collection_seconds / 60:.1f} minutes "
        f"across {len(manifest['records'])} shards.")
    add("")

    add("## Execution log")
    add("")
    add("Verbatim from `outputs/three_head/run_log.txt`.")
    add("")
    add("```text")
    lines.extend(log_excerpt(run_log))
    add("```")
    add("")

    add("## Directory layout")
    add("")
    add("```text")
    add("three_head/                        the pipeline (self-contained)")
    add("  core.py                          collection, protocol, atomic writes")
    add("  features.py                      analytic pre-ADC moment features")
    add("  structure.py                     coordinate sharing + analytic covariance")
    add("  structured_correlation.py        the source factor model")
    add("  training.py                      all three heads, scheduled")
    add("  evaluation.py                    metrics, ablations, report")
    add("  metrics.py                       shared metric definitions")
    add("  conditional_mean.py   \\")
    add("  observable_dpe.py      >          vendored model and tail code")
    add("  tail.py               /")
    add("configs/three_head_protocol.json   the single source of truth")
    add("scripts/run_three_head.py          the entry point")
    add("scripts/write_summary.py           regenerates this document")
    add("tests/test_three_head.py           self-containment + pipeline + structure")
    add("outputs/three_head/                everything this pipeline writes")
    add("memintelli_surrogate_comparison/   the frozen upstream simulator, and the")
    add("                                   three files the protocol pins by hash")
    add("docs/                              this document and the longer write-ups")
    add("```")
    add("")
    add("### Artifacts not in this repository")
    add("")
    add("`outputs/three_head/context_shards/` holds about 254 MB of collected Exact")
    add("samples and is excluded. The `collect` stage regenerates it deterministically")
    add("from the protocol seeds, and the checkpoints and reports published here were")
    add("produced from exactly those shards.")
    add("")

    add("## Dependencies")
    add("")
    add("The `three_head` package imports only the standard library, `torch`, and")
    add("`memintelli.pimpy` — the frozen upstream device simulator. That simulator is")
    add("a third-party snapshot, vendored unmodified under")
    add("`memintelli_surrogate_comparison/upstream/` together with its license file,")
    add("and it is the only path the runner adds besides this directory. See the")
    add("repository README for attribution and a note on its licensing. No sibling")
    add("experiment folder is imported, and a test asserts this.")
    add("")

    add("## What this does not show")
    add("")
    for item in results["limitations"]:
        add(f"- {item}")
    add("")

    (EXPERIMENT_ROOT / "docs" / "SUMMARY.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    print(f"docs/SUMMARY.md written: {len(lines)} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
